### ISSUE TITLE
t-deck i2s audio

### ISSUE THREAD

**Issue by dosuserx** [RetiredWizard/PyDOS#12]
hey. firstly i really appreciate you supporting the lilygo t-deck. i have run into a few issues and i was wondering if there is a fix for them i could be finding.

1. path changes every reboot. this would be a very small problem if the t-deck keyboard had a $ key but it doesn't. i have to use serial monitor to change it. it wont stay. i tried adding the command to the autoexec.bat but it doesn't work quite right.
2. the t-deck's speaker is connected thru i2s not pwm. im still learning how to port this over, any help would be appreciated.
3. i can not figure out how to mount an sd card. im pretty sure im typing in the command your code wants "sdmount /sd,0" but it just says its took to long waiting. can you explain how exactly to mount an sd card? im stuck.

otherwise im having a fantastic time messing with dos. id love to port some terminal proggies. its been a personal dream of mine to have a blackberry with dos scripts instead of apps. this has made my dream come true. 

thank you for your time.

**Comment by RetiredWizard** [comment]
Hello @dosuserx, I'm glad you're enjoying PyDOS, it's been lots of fun to work on.

1) I probably should have documented it better, but I used the Speaker key (just left of the enter key) for the dollar sign ($).

2) I just uploaded an i2s test program that plays .wav files to the [tdeck_repl](https://github.com/RetiredWizard/tdeck_repl/blob/main/playi2s.py) repository. I converted my test .wav files to a simple format that is described in the comments at the start of the program.

3) If you haven't wired anything else up on the spi bus the command you indicated should mount the card fine, in fact you should be able to simply use the sdmount command without any parameters. If you're using the latest Circuit Python version (9.0 Beta 0) and the sdmount from the most recent PyDOS upload, you'll need to create the mount point directory (/sd) before trying to mount the SD card. Earlier versions required that no /sd directory exist. If the mount point requirement was an issue you should have received a more informative error though so that's probably not your issue.

I have seen a lot of issues with individual SD cards. If you have a second card you can try, I'd try that first. Make sure the cards are formatted with a FAT file system and you probably want to use the smallest card you can find (although I have had problems with cards less than 1 GB. I think technically the >8GB and <1GB should work, I've just had better luck with the 4-8 GB sized cards.

**Comment by RetiredWizard** [comment]
I did plan to update the PyDOS sound applets to work with i2s at some point, but it's sort of a low priority. The code snippet from the [Circuit Python Docs](https://docs.circuitpython.org/en/latest/shared-bindings/audiobusio/index.html) does generate a tone on the t-deck if you replace the `i2s = audiobus....` line with
```i2s = audiobusio.I2SOut(board.SPEAKER_SCK, board.SPEAKER_WS, board.SPEAKER_DOUT)```

**Comment by RetiredWizard** [comment]
Even more fun :grin:
```py
import synthio
import audiobusio
import board

i2s = audiobusio.I2SOut(board.SPEAKER_SCK, board.SPEAKER_WS, board.SPEAKER_DOUT)

melody = synthio.MidiTrack(b"\0\x90H\0*\x80H\0\6\x90J\0*\x80J\0\6\x90L\0*\x80L\0\6\x90J\0" +
                           b"*\x80J\0\6\x90H\0*\x80H\0\6\x90J\0*\x80J\0\6\x90L\0T\x80L\0" +
                           b"\x0c\x90H\0T\x80H\0\x0c\x90H\0T\x80H\0", tempo=640)

i2s.play(melody)
```

**Comment by RetiredWizard** [comment]
I have a lot to learn about synthio but I think this is where I'll start to update the PyDOS sound applets:
```py
import synthio
import audiobusio
import board
import time

i2s = audiobusio.I2SOut(board.SPEAKER_SCK, board.SPEAKER_WS, board.SPEAKER_DOUT)
synth = synthio.Synthesizer(sample_rate=22050)
e = synthio.Envelope(attack_time=0,decay_time=0,release_time=0,attack_level=.3,sustain_level=.3)
note = synthio.Note(frequency=261.626,envelope=e)

i2s.play(synth)

synth.press(note)
time.sleep(1)
synth.release(note)
```

**Comment by RetiredWizard** [comment]
I added the dollar sign information to the equal sign and square brackets documentation in the [tdeck_repl](https://github.com/RetiredWizard/tdeck_repl) repository readme file.

**Comment by dosuserx** [comment]
![IMG_20240213_111732708](https://github.com/RetiredWizard/PyDOS/assets/12874047/09455e4f-79ba-4bfa-876f-68fa3b48213a)
i feel pretty stupid now. my bad. i have a learning disability. thanks though. pydos is awesome. I'm really enjoying it.

**Comment by RetiredWizard** [comment]
Interesting...

Even if you didn't need the added documentation, it looks like some of the devices don't have the $ printed on the keyboard :grin:

![IMG_20240213_152310307_HDR](https://github.com/RetiredWizard/PyDOS/assets/29083569/b1ef2a3c-353f-44c2-a0e4-3315f38cf810)

**Comment by RetiredWizard** [comment]
Thanks for push, it was what I needed to get I2S audio working with the PyDOS applets. I just pushed some updates to PyDOS that include I2S audio support for the PyDOS **sound**, **tsound** and **piano** apps.
